# created by init task for use with github actons
target_repo: quay.io/bradfordwagner/ansible
upstreams:
  - { repo: quay.io/bradfordwagner/base:3.0.0-alpine_3.18      , platforms: [linux/amd64      , linux/arm64] , os: alpine }
  - { repo: quay.io/bradfordwagner/base:3.0.0-alpine_3.19      , platforms: [linux/amd64      , linux/arm64] , os: alpine }
  - { repo: quay.io/bradfordwagner/base:3.0.0-archlinux_latest , platforms: [linux/amd64    ] , os: arch }
  - { repo: quay.io/bradfordwagner/base:3.0.0-debian_bookworm  , platforms: [linux/amd64      , linux/arm64] , os: debian }
  # bullseye's latest support is 8.7.0, whilst everything supports 9.3.0
  # - { repo: quay.io/bradfordwagner/base:3.0.0-debian_bullseye  , platforms: [linux/amd64      , linux/arm64] , os: debian }

  - { repo: quay.io/bradfordwagner/base:3.0.0-ubuntu_mantic    , platforms: [linux/amd64        , linux/arm64], os: debian }
  - { repo: quay.io/bradfordwagner/base:3.0.0-ubuntu_noble     , platforms: [linux/amd64        , linux/arm64], os: debian }
