# created by init task for use with github actons
target_repo: ghcr.io/bradfordwagner/ansible
upstream:
  repo: ghcr.io/bradfordwagner/base
  tag: 3.3.0
builds:
  # - { os: alpine_3.18      , platforms: [linux/amd64      , linux/arm64]        , pkg_installer: alpine }
  # - { os: alpine_3.19      , platforms: [linux/amd64      , linux/arm64]        , pkg_installer: alpine }
  # - { os: archlinux_latest , platforms: [linux/amd64    ] , pkg_installer: arch }
  # - { os: debian_bookworm  , platforms: [linux/amd64      , linux/arm64]        , pkg_installer: debian }
  # - { os: ubuntu_mantic    , platforms: [linux/amd64      , linux/arm64]        , pkg_installer: debian }
  # - { os: ubuntu_noble     , platforms: [linux/amd64      , linux/arm64]        , pkg_installer: debian }
  - { os: alpine_3.18      , platforms: [linux/amd64      ]        , pkg_installer: alpine }
  - { os: alpine_3.19      , platforms: [linux/amd64      ]        , pkg_installer: alpine }
  - { os: archlinux_latest , platforms: [linux/amd64    ] , pkg_installer: arch }
  - { os: debian_bookworm  , platforms: [linux/amd64      ]        , pkg_installer: debian }
  - { os: ubuntu_mantic    , platforms: [linux/amd64      ]        , pkg_installer: debian }
  - { os: ubuntu_noble     , platforms: [linux/amd64      ]        , pkg_installer: debian }
  # bullseye's latest support is 8.7.0, whilst everything supports 9.3.0
  # - { os: debian_bullseye  , platforms: [linux/amd64      , linux/arm64] , pkg_installer: debian }
