---
- hosts: localhost
  roles:
    - role: andrewrothstein.ca_certs
  tasks:
    - name: smoketest installed binaries are added to path
      command: "{{ item }}"
      loop:
        - ansible --version
        - ansible-galaxy --version
        - ansible-playbook --version
        - git version
