apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ansible-image-
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: git_ref_type
        value: branches
      - name: git_version
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_version
      - name: git_ref_type
      - name: upstream_repo
        value: quay.io/bradfordwagner/base
      - name: upstream_tag
        value: 2.1.0
      - name: repo_name
        value: quay.io/bradfordwagner/ansible
    dag:
      tasks:
      - name: custom-dockerfile
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/container-ansible
          - name: git_version
            value: "{{ inputs.parameters.git_version }}"
          - name: upstream_repo
            value: "{{ inputs.parameters.upstream_repo }}"
          - name: upstream_tag
            value: "{{ inputs.parameters.upstream_tag }}-{{ item.platform }}"
          - name: repo_name
            value: "{{ inputs.parameters.repo_name }}"
          - name: runtime_platforms
            value: "{{ item.runtime_platforms }}"
          - name: platform
            value: "{{ item.platform }}"
          - name: dockerfile
            value: |
              ENV LANG C.UTF-8
              ENV LC_ALL C.UTF-8
              ENV ANSIBLE_OS {{ item.os }}
              ENV HOME /root
              WORKDIR ${HOME}
              COPY . .
              RUN . ./ansible-install-lib; install_{{ item.os }}_{{ item.dashver }}
              COPY ./ansible-destroy     /usr/local/bin
              RUN rm -rf * # cleanup
        templateRef:
          name: flavor-custom-dockerfile-template
          template: "{{ inputs.parameters.git_ref_type }}"
        withItems:
        - { os: alpine, platform: alpine_3.13    , dashver: 3_13    , runtime_platforms: [linux/amd64, linux/386] }
        - { os: alpine, platform: alpine_3.14    , dashver: 3_14    , runtime_platforms: [linux/amd64, linux/386] }
        - { os: ubuntu, platform: ubuntu_bionic  , dashver: bionic  , runtime_platforms: [linux/amd64, linux/386]  }
        - { os: debian, platform: debian_buster  , dashver: buster  , runtime_platforms: [linux/amd64, linux/386] }
        - { os: debian, platform: debian_bullseye, dashver: bullseye, runtime_platforms: [linux/amd64, linux/386] }
        # missing from registry
        # - { os: ubuntu, platform: ubuntu_focal   , dashver: focal   , runtime_platforms: [linux/amd64, linux/arm, linux/arm64, linux/ppc64le, linux/riscv64 , linux/s390x] }

