apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ansible-image-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: tag
      value: latest
    - name: repo_name
      value: quay.io/bradfordwagner/ansible
    - name: push
      value: "--no-push"
    - name: upstream_repo
      value: quay.io/bradfordwagner/base
    - name: upstream_tag
      value: 1.0.0
  templates:
  - name: main
    inputs:
      parameters:
      - name: upstream_repo
      - name: upstream_tag
      - name: repo_name
    dag:
      tasks:
      - name: custom-dockerfile
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/container-ansible.git
          - name: git_version
            value: feature/import-script
          - name: upstream_repo
            value: "{{ inputs.parameters.upstream_repo }}"
          - name: upstream_tag
            value: "{{ inputs.parameters.upstream_tag }}-{{ item.platform }}"
          - name: repo_name
            value: "{{ inputs.parameters.repo_name }}"
          - name: dockerfile
            value: |
              FROM {{ inputs.parameters.upstream_repo }}:{{ inputs.parameters.upstream_tag }}-{{ item.platform }}
              COPY install_ansible.sh /usr/local/bin
              RUN . /usr/local/bin/install_ansible.sh; {{ item.os }}
        templateRef:
          name: flavor-custom-dockerfile-template
          template: main
        withItems:
#       - { os: alpine, platform: 'alpine_3.12' }
#       - { os: alpine, platform: 'alpine_3.13' }
#       - { os: alpine, platform: 'alpine_3.14' }
        - { os: ubuntu, platform: 'ubuntu_bionic' }
#       - { os: ubuntu, platform: 'ubuntu_focal' }

