apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ansible-image-
spec:
  entrypoint: build-ansible-image
  arguments:
    parameters:
    - name: tag
      value: latest
    - name: upstream_tag
      value: 1.0.0
    - name: repo_name
      value: quay.io/bradfordwagner/ansible
    - name: push
      value: "--no-push"
    - name: base_image
      value: quay.io/bradfordwagner/base
  templates:
  - name: build-ansible-image
    inputs:
      parameters:
      - name: tag
      - name: upstream_tag
      - name: repo_name
      - name: push
      - name: base_image
    dag:
      tasks:
      - name: alpine
        templateRef:
          name: kaniko-template
          template: main
        arguments:
          parameters:
          - name: repo_name
            value: "{{inputs.parameters.repo_name}}"
          - name: tag
            value: "{{inputs.parameters.tag}}-{{item.platform}}"
          - name: push
            value: "{{inputs.parameters.push}}"
          - name: dockerfile
            value: |
              FROM {{inputs.parameters.base_image}}:{{inputs.parameters.upstream_tag}}-{{item.platform}}
              RUN apk add git \
                          ansible
        withItems:
        - { platform: 'alpine_3.12' }
        - { platform: 'alpine_3.13' }
        - { platform: 'alpine_3.14' }
      - name: ubuntu
        templateRef:
          name: kaniko-template
          template: main
        arguments:
          parameters:
          - name: repo_name
            value: "{{inputs.parameters.repo_name}}"
          - name: tag
            value: "{{inputs.parameters.tag}}-{{item.platform}}"
          - name: push
            value: "{{inputs.parameters.push}}"
          - name: dockerfile
            value: |
              FROM {{inputs.parameters.base_image}}:{{inputs.parameters.upstream_tag}}-{{item.platform}}
              RUN apt update
              RUN apt install software-properties-common -y
              RUN add-apt-repository -y --update ppa:ansible/ansible
              RUN apt install ansible -y
        withItems:
        - { platform: 'ubuntu_bionic' }
        - { platform: 'ubuntu_focal' }
