apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ansible-image-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: tag
      value: latest
    - name: repo_name
      value: quay.io/bradfordwagner/ansible
    - name: push
      value: "--no-push"
    - name: upstream_repo
      value: quay.io/bradfordwagner/base
    - name: upstream_tag
      value: 1.0.0
  templates:
  - name: main
    inputs:
      parameters:
      - name: upstream_repo
      - name: upstream_tag
      - name: repo_name
    dag:
      tasks:
      - name: custom-dockerfile
        arguments:
          parameters:
          - name: git_repo
            value: https://github.com/bradfordwagner/container-ansible.git
          - name: git_version
            value: feature/import-script
          - name: upstream_repo
            value: "{{ inputs.parameters.upstream_repo }}"
          - name: upstream_tag
            value: "{{ inputs.parameters.upstream_tag }}-{{ item.platform }}"
          - name: repo_name
            value: "{{ inputs.parameters.repo_name }}"
          - name: dockerfile
            value: |
              FROM {{ inputs.parameters.upstream_repo }}:{{ inputs.parameters.upstream_tag }}-{{ item.platform }}
              RUN echo custom ansible build
              COPY install_ansible.sh /usr/local/bin
              RUN ls /usr/local/bin
        templateRef:
          name: flavor-custom-dockerfile-template
          template: main
        withItems:
        - { platform: 'alpine_3.12' }
#       - { platform: 'alpine_3.13' }
#       - { platform: 'alpine_3.14' }
        - { platform: 'ubuntu_bionic' }
#       - { platform: 'ubuntu_focal' }


  # working import from prev stage
# - name: echo
#   inputs:
#     artifacts:
#     - name: git
#       path: /tmp/src
#     parameters:
#     - name: message
#   container:
#     image: alpine
#     command: [sh]
#     args:
#     - -lc
#     - |
#       ls -lh /tmp/src
#       cat /tmp/src/README.md
# - name: build-ansible-image
#   inputs:
#     parameters:
#     - name: tag
#     - name: upstream_tag
#     - name: repo_name
#     - name: push
#     - name: base_image
#   dag:
#     tasks:
#     - name: alpine
#       templateRef:
#         name: git-template
#         template: main
#     - name: echo-readme
#       arguments:
#         artifacts:
#         - name: git
#           from: "{{tasks.alpine.outputs.artifacts.git}}" # this is the line giving me problems
#         parameters: [{name: message, value: 'hello world'}]
#       dependencies: [alpine]
#       template: echo



#       templateRef:
#         name: kaniko-template
#         template: main
#       arguments:
#         parameters:
#         - name: repo_name
#           value: "{{inputs.parameters.repo_name}}"
#         - name: tag
#           value: "{{inputs.parameters.tag}}-{{item.platform}}"
#         - name: push
#           value: "{{inputs.parameters.push}}"
#         - name: dockerfile
#           value: |
#             FROM {{inputs.parameters.base_image}}:{{inputs.parameters.upstream_tag}}-{{item.platform}}
#             RUN apk add git \
#                         ansible
#       withItems:
#       - { platform: 'alpine_3.12' }
#       - { platform: 'alpine_3.13' }
#       - { platform: 'alpine_3.14' }
#     - name: ubuntu
#       templateRef:
#         name: kaniko-template
#         template: main
#       arguments:
#         parameters:
#         - name: repo_name
#           value: "{{inputs.parameters.repo_name}}"
#         - name: tag
#           value: "{{inputs.parameters.tag}}-{{item.platform}}"
#         - name: push
#           value: "{{inputs.parameters.push}}"
#         - name: dockerfile
#           value: |
#             FROM {{inputs.parameters.base_image}}:{{inputs.parameters.upstream_tag}}-{{item.platform}}
#             RUN apt update
#             RUN apt install software-properties-common -y
#             RUN add-apt-repository -y --update ppa:ansible/ansible
#             RUN apt install ansible -y
#       withItems:
#       - { platform: 'ubuntu_bionic' }
#       - { platform: 'ubuntu_focal' }
