apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ansible-image-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: git_version
      value: main
    - name: tag
      value: latest
    - name: repo_name
      value: quay.io/bradfordwagner/ansible
    - name: push
      value: ""
    - name: upstream_repo
      value: quay.io/bradfordwagner/base
    - name: upstream_tag
      value: 1.2.0
  templates:
  - name: main
    inputs:
      parameters:
      - name: git_version
      - name: tag
      - name: upstream_repo
      - name: upstream_tag
      - name: repo_name
      - name: push
    dag:
      tasks:
      - name: custom-dockerfile
        arguments:
          parameters:
          - name: git_repo
            # forked from: https://github.com/andrewrothstein/docker-ansible.git
            value: https://github.com/bradfordwagner/docker-ansible.git
          - name: git_version
            value: feature/destroy
          - name: upstream_repo
            value: "{{ inputs.parameters.upstream_repo }}"
          - name: upstream_tag
            value: "{{ inputs.parameters.upstream_tag }}-{{ item.platform }}"
          - name: repo_name
            value: "{{ inputs.parameters.repo_name }}"
          - name: push
            value: "{{ inputs.parameters.push }}"
          - name: tag
            value: "{{ inputs.parameters.tag }}-{{ item.platform }}"
          - name: dockerfile
            value: |
              FROM {{ inputs.parameters.upstream_repo }}:{{ inputs.parameters.upstream_tag }}-{{ item.platform }}
              ENV LANG C.UTF-8
              ENV LC_ALL C.UTF-8
              ENV ANSIBLE_OS {{ item.os }}
              ENV HOME /root
              WORKDIR ${HOME}
              COPY . .
              RUN . ./ansible-install-lib; install_{{ item.os }}_{{ item.dashver }}
              COPY ./ansible-destroy     /usr/local/bin
              RUN rm -rf * # cleanup
        templateRef:
          name: flavor-custom-dockerfile-template
          template: main
        withItems:
        - { os: alpine, platform: 'alpine_3.13', dashver: "3_13" }
        - { os: alpine, platform: 'alpine_3.14', dashver: "3_14" }
        - { os: ubuntu, platform: ubuntu_bionic, dashver: bionic }
        - { os: ubuntu, platform: ubuntu_focal, dashver: focal }
        - { os: debian, platform: debian_buster, dashver: buster }
        - { os: debian, platform: debian_bullseye, dashver: bullseye }

